### ISSUE TITLE
Include in Stock Helix

### ISSUE THREAD

**Issue by undersquire** [mrmcc3/yo-theme-helix#4]
Hey I really like these themes, and I think it would be great if they could be included in Helix by default. Would you be willing to open an issue/PR to add these into Helix?

**Comment by mrmcc3** [comment]
Thanks. I've been meaning to improve these themes with some new theme keys that helix has added. If I find some time after that I can open a PR

**Comment by mrmcc3** [comment]
FYI i've updated the themes to highlight new helix features like jump labels and fixed a few other things that weren't ideal. I opened a PR to include `yo` `yo_light` and `yo_berry` in helix.

**Comment by mrmcc3** [comment]
PR merged
